
import { GoogleGenAI } from "@google/genai";
import { removeWhiteBackground, centerAndMaximizeSticker } from "../utils/imageUtils";
import { StickerVariation } from "../types";

const apiKey = process.env.API_KEY || "";
// Initialize AI safely. If no key, we will warn but not crash the UI immediately.
const ai = apiKey ? new GoogleGenAI({ apiKey }) : null;

const STYLE_PROMPT = `
  STYLE GUIDE:
  - VISUAL STYLE: 3D glossy render, cute toy-like finish, volumetric lighting, smooth plastic texture.
  - MATERIAL: Shiny vinyl or plastic.
  - LIGHTING: Soft, bright, volumetric studio lighting.
  - BACKGROUND: Solid pure white background (FFFFFF). Ensure high contrast separation between subject and background.
  - COMPOSITION: Subject MUST be perfectly CENTERED in the frame.
  - SHADOWS: NO cast shadows on the ground. NO floor reflections. The object must appear to be floating in a void.
  - LAYOUT: The output must ALWAYS be a self-contained object/character/diorama floating in white space. NO floor, NO horizon line, NO rectangular scenes.
`;

const processGeneratedImage = async (base64Data: string): Promise<string> => {
  const rawImage = `data:image/png;base64,${base64Data}`;
  const transparentImage = await removeWhiteBackground(rawImage);
  return await centerAndMaximizeSticker(transparentImage);
};

export const generate3DSticker = async (imageBase64: string): Promise<string> => {
  if (!ai) {
    console.warn("DEMO MODE: No API Key found. Returning mock response.");
    await new Promise(resolve => setTimeout(resolve, 2000)); // Simulate work

    // Return a mock base64 image (a simple blue dot or similar placeholder to prove it works)
    // In a real demo, you'd replace this string with a nice pre-generated 3D sticker base64.
    return "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";
  }
  try {
    const base64Data = imageBase64.replace(/^data:image\/\w+;base64,/, "");
    const mimeType = imageBase64.match(/^data:(image\/\w+);base64,/)?.[1] || "image/jpeg";
    const model = 'gemini-2.5-flash-image';

    const prompt = `
      Create a 3D rendered sticker based on the content of this photo.
      
      ${STYLE_PROMPT}
      
      CONTENT & FRAMING:
      - Analyze the image to identify the main content (Person, Animal, Object, or Landscape/Scene).
      - Transform it into a "CUTE VERSION" of itself.
      
      CRITICAL - SUBJECT TYPES:
      - If Person: Create a cute toy-like character. Full body. Shiny plastic texture.
      - If Animal/Object: Create a cute 3D toy-like version. Shiny plastic texture.
      - If Landscape/Scene: Create a cute 3D glossy ISOMETRIC DIORAMA or miniature world.

      CRITICAL - FULL BODY & EXTRAPOLATION:
      - If input is cropped, EXTRAPOLATE and invent the rest of the body to create a COMPLETE FULL-BODY FIGURE.
      - Do not generate just a head or bust.

      DETAILS & ACCURACY:
      - Match hair color, style, glasses, and key identifying features exactly.
      - Match colors and mood.
      
      CRITICAL COMPOSITION:
      - ISOLATED on white background.
      - CENTER the subject perfectly in the middle of the frame.
      - EXTREME CLOSE CROP (maximize size in frame).
    `;

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          { inlineData: { mimeType, data: base64Data } },
          { text: prompt },
        ],
      },
    });

    if (response.candidates && response.candidates.length > 0) {
      const parts = response.candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return await processGeneratedImage(part.inlineData.data);
        }
      }
    }
    throw new Error("No image generated by Gemini.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const tweakSticker = async (currentStickerBase64: string, instruction: string): Promise<string> => {
  if (!ai) throw new Error("DEMO MODE: API Key missing.");
  try {
    const base64Data = currentStickerBase64.replace(/^data:image\/\w+;base64,/, "");
    const mimeType = currentStickerBase64.match(/^data:(image\/\w+);base64,/)?.[1] || "image/png";
    const model = 'gemini-2.5-flash-image';

    const prompt = `
      Edit this 3D sticker based on the user's request.
      USER REQUEST: "${instruction}"
      
      ${STYLE_PROMPT}
      
      IMPORTANT:
      - Keep the exact same pose and character design, only apply the requested change.
      - Background must remain SOLID WHITE.
      - Maintain 3D glossy plastic style.
      - Ensure the subject remains CENTERED.
      - Ensure it remains FULL BODY if currently full body.
    `;

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          { inlineData: { mimeType, data: base64Data } },
          { text: prompt },
        ],
      },
    });

    if (response.candidates && response.candidates.length > 0) {
      const parts = response.candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return await processGeneratedImage(part.inlineData.data);
        }
      }
    }
    throw new Error("No image generated by Gemini.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const generateStickerVariations = async (sourceImageBase64: string): Promise<StickerVariation[]> => {
  if (!ai) return [];
  const emotions = ["Happy", "Love", "Cool", "Sad", "Angry"];
  const base64Data = sourceImageBase64.replace(/^data:image\/\w+;base64,/, "");
  const mimeType = sourceImageBase64.match(/^data:(image\/\w+);base64,/)?.[1] || "image/jpeg";
  const model = 'gemini-2.5-flash-image';

  const generateVariation = async (emotion: string): Promise<StickerVariation | null> => {
    const prompt = `
      Create a 3D CUTE STICKER variation of the character/subject in this photo.
      EMOTION/ACTION: ${emotion}.

      ${STYLE_PROMPT}

      CRITICAL - CONSISTENCY:
      - It MUST look like the EXACT SAME CHARACTER as the source image (same hair, same glasses, same outfit, same face features).
      - Maintain the same "Cute 3D Toy" style.

      CRITICAL - FULL BODY & POSE:
      - GENERATE THE FULL BODY. Do NOT generate just a head/bust.
      - Use the WHOLE BODY to express the emotion (e.g., jumping for happy, slouching for sad).
      - If the source image is cropped, EXTRAPOLATE the rest of the body and matching outfit.
      
      LAYOUT:
      - NO FLOORS, NO BACKGROUNDS. Floating object in white space.
    `;

    try {
      const response = await ai.models.generateContent({
        model: model,
        contents: {
          parts: [
            { inlineData: { mimeType, data: base64Data } },
            { text: prompt },
          ],
        },
      });

      if (response.candidates?.[0]?.content?.parts) {
        const parts = response.candidates[0].content.parts;
        for (const part of parts) {
          if (part.inlineData && part.inlineData.data) {
            const finalizedImage = await processGeneratedImage(part.inlineData.data);
            return { emotion, image: finalizedImage };
          }
        }
      }
    } catch (e) {
      console.error(`Failed to generate ${emotion} variation`, e);
    }
    return null;
  };

  // Run in parallel
  const results = await Promise.all(emotions.map(generateVariation));
  return results.filter((r): r is StickerVariation => r !== null);
};
